### ISSUE TITLE
Vote Step div sometimes shrinking into bottom right

### ISSUE THREAD

**Issue by nscramer** [roadtrippers/kami_widget#3]
The original widget div (vote step) is getting shrunken down to "" content. This is appearing randomly for Nick on Chrome 66.0.3359.139 on macOS 10.13.4. 

![default](https://user-images.githubusercontent.com/4441926/39874729-a8b908e8-543c-11e8-87c3-18852454b6cd.jpg)

**Comment by nscramer** [comment]
A pattern I’ve picked up on: I can now reliably reproduce blue square if it’s the first time I’ve loaded that POI. So if you pick a random place you’ve never loaded before and then submit a vote without hitting refresh, you should get it

**Comment by eriknomitch** [comment]
Fixed, thanks @nscramer.
